AWSTemplateFormatVersion: '2010-09-09'
Description: |
  GitHub OIDC Provider - Deploy ONCE per AWS account.
  This allows GitHub Actions to authenticate without storing AWS credentials.

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

Outputs:
  OIDCProviderArn:
    Description: ARN of the GitHub OIDC provider (use this in role templates)
    Value: !GetAtt GitHubOIDCProvider.Arn
    Export:
      Name: GitHubOIDCProviderArn
